package cmd

const (
	// Error Code constants
	CONN_RESET   = "CONN_RESET"
	CONN_BLOCKED = "CONN_BLOCKED"
	CONN_UNKNOWN = "CONN_UNKNOWN"
	CONN_TIMEOUT = "CONN_TIMEOUT"
	NO_SUCH_HOST = "NO_SUCH_HOST"
	OTHER_ERROR  = "OTHER_ERROR"

	// Censorship Methods
	NO_FILTERING   = "NO_FILTERING"
	HTTP_FILTERING = "HTTP_FILTERING"
	DNS_FILTERING  = "DNS_FILTERING"
	IP_FILTERING   = "IP_FILTERING"
	SNI_FILTERING  = "SNI_FILTERING"

	// HTTP Client Constants
	MAX_RETRIES = 3
)
